import casualImage from './../src/images/casual-cover.jpg';
import casualCat from './../src/images/casual-cat.jpg';
import lisa from './images/lisa.jpg';
import freddie from './images/freddie.jpg';
import russel from './images/russel.jpg';
import categoryCasual from './images/category-casual.jpg';
import categoryActive from './images/category-active.jpg';
import categoryLeather from './images/category-leather.jpg';
import activeCover from './images/active-cover.jpg';
import leatherCover from './images/leather-cover.jpg';

const sliderItems = [
	{
		id: 1,
		img: `${casualImage}`,
		title: 'CASUAL WEARS',
		desc: "DON'T COMPROMISE ON STYLE! GET CUSTOMIZED DESIGNS FOR YOUR BRAND",
		bg: 'DFF6FF',
	},
	{
		id: 2,
		img: `${activeCover}`,
		title: 'ACTIVE WEARS',
		desc: 'MADE WITH PREMIUM QUALITY FABRICS TO ENDURE ANY WORKOUT!',
		bg: 'A2DBFA',
	},
	{
		id: 3,
		img: `${leatherCover}`,
		title: 'LEATHER WEARS',
		desc: 'FINEST QUALITY LEATHER USED TO GET PREMIUM FASHION AND LUXURY!',
		bg: 'C0FEFC',
	},
];

const navigation = [
	{ id: 1, name: 'HOME', path: '/' },
	{
		id: 2,
		name: 'ABOUT',
		path: '/about',
	},
	{
		id: 3,
		name: 'PRODUCTS',
		path: '#',
	},
	{
		id: 4,
		name: 'CUSTOM ORDER',
		path: '/customorder',
	},
	{
		id: 5,
		name: 'CONTACT US',
		path: '/contact',
	},
	{
		id: 6,
		name: 'HELP',
		path: '/help',
	},
];

const productsDropdown = [
	{ id: 1, name: 'CASUAL WEAR', path: '/casualwear', img: `${categoryCasual}` },
	{ id: 2, name: 'ACTIVE WEAR', path: '/activewear', img: `${categoryActive}` },
	{ id: 3, name: 'LEATHER WEAR', path: '/leatherwear', img: `${categoryLeather}` },
];

const popularProducts = [
	{
		id: 1,
		mainCategory: 'TEAMWEAR',
		subCategory: 'uniforms',
		productName: 'soccer set',
		article: 'TC-07',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 2,
		mainCategory: 'CASUALWEAR',
		subCategory: 'T-shirts',
		productName: 'V-neck T-shirt',
		article: 'TC-08',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 3,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Sweatshirts',
		productName: 'Plain Sweatshirt',
		article: 'TC-09',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 4,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Sweatshirts',
		productName: 'Camo Sweatshirt',
		article: 'TC-10',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 5,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Plain Legging',
		article: 'TC-11',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 6,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Sublimated Legging',
		article: 'TC-12',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 7,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Loose fit Shorts',
		article: 'TC-13',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
	{
		id: 8,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Double Shorts',
		article: 'TC-14',
		subCategoryImg: `${casualImage}`,
		productImg: `${casualImage}`,
	},
];

const subCat = [
	{
		id: 1,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
	{
		id: 2,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
	{
		id: 3,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
	{
		id: 4,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
	{
		id: 5,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
	{
		id: 6,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
	{
		id: 7,
		name: 'HOODIES',
		img: `${casualImage}`,
	},
];

const HoodieList = [
	{
		id: 1,
		article: 'TC-01',
		img: `${casualImage}`,
	},
	{
		id: 2,
		article: 'TC-02',
		img: `${casualImage}`,
	},
	{
		id: 3,
		article: 'TC-03',
		img: `${casualImage}`,
	},
	{
		id: 4,
		article: 'TC-04',
		img: `${casualImage}`,
	},
	{
		id: 5,
		article: 'TC-05',
		img: `${casualImage}`,
	},
	{
		id: 6,
		article: 'TC-06',
		img: `${casualImage}`,
	},
];

const allProducts = [
	{
		id: 1,
		cat: 'HOODIES',
		name: 'PULLOVER HOODIE',
		img: `${casualImage}`,
		art: 'TC-01',
	},
	{ id: 2, cat: 'Hoodies', name: 'Printed HOODIE', img: `${casualImage}`, art: 'TC-02' },
	{
		id: 3,
		cat: 'HOODIES',
		name: 'SUBLIMATED HOODIE',
		img: `${casualImage}`,
		art: 'TC-03',
	},
	{
		id: 4,
		cat: 'TRACKSUITS',
		name: 'Tracksuit',
		img: `${casualImage}`,
		art: 'TC-04',
	},
	{
		id: 5,
		cat: 'JOGGERS',
		name: 'Jogger',
		img: `${casualImage}`,
		art: 'TC-05',
	},
];

const ReviewData = [
	{
		img: `${freddie}`,
		client: 'Freddie Long',
		review: 'I was looking for a custom clothing manufacturer and I am very happy that I found Trade City. Very satisfied!',
	},
	{
		img: `${lisa}`,
		client: 'Lisa',
		review: 'Awesome Work done by the team! I am ordering again!',
	},
	{
		img: `${russel}`,
		client: 'Russel',
		review: 'Finally found the perfect manufacturer! On time delivery and I am really satisfied by the quality!',
	},
];

const finalData = [
	{
		id: 1,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Hoodies',
		productName: 'Pullover Hoodie',
		article: 'P-H-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183432/pentago/hoodies/hoodie-p1_rg8ab1.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 2,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Hoodies',
		productName: 'Washed Hoodie',
		article: 'P-H-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183432/pentago/hoodies/Washedhoodie-p2_ldpesx.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 3,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Hoodies',
		productName: 'Loose Fit Hoodie',
		article: 'P-H-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183433/pentago/hoodies/LooseFit-p6_y1rxnc.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 4,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Hoodies',
		productName: 'Camo Hoodie',
		article: 'P-H-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183433/pentago/hoodies/CustomCamo-p4_y2z46x.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 5,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Hoodies',
		productName: 'High Zipper Hoodie',
		article: 'P-H-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183436/pentago/hoodies/highZipper-p3_pfoe2t.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 6,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Hoodies',
		productName: 'Camo Hoodie',
		article: 'P-H-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183432/pentago/hoodies/CustomCamo-p5_ricgiq.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 7,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Customized Tracksuit',
		article: 'P-T-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183500/pentago/tracksuits/Tracksuit-p6_nmt1xw.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 8,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Customized Tracksuit',
		article: 'P-T-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183497/pentago/tracksuits/Tracksuit-p4_dzhxha.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 9,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Customized Tracksuit',
		article: 'P-T-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p3_flhmrb.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 10,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Polyester Tracksuit',
		article: 'P-T-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p5_htejnn.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 11,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Plain Tracksuit',
		article: 'P-T-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p1_yk7ugd.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 12,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Custom Tracksuit',
		article: 'P-T-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p9_w7ecg3.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 13,
		mainCategory: '	CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Custom Tracksuit',
		article: 'P-T-07',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p2_uzqaqu.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 14,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Custom Tracksuit',
		article: 'P-T-08',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p8_fqfrfw.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 15,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tracksuits',
		productName: 'Custom Tracksuit',
		article: 'P-T-09',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183496/pentago/tracksuits/Tracksuit-p7_wqw9nd.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 16,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Jackets',
		productName: 'Puffer jacket',
		article: 'P-J-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183617/pentago/jackets/jacket-p5_bp1h9f.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 17,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Jackets',
		productName: 'Custom Puffer Jacket',
		article: 'P-J-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183617/pentago/jackets/jacket-p1_a7irth.jpg`,
		subCategoryImg: `${casualImage}`,
	},

	{
		id: 18,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Jackets',
		productName: 'Custom Sublimated Jacket',
		article: 'P-J-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183617/pentago/jackets/jacket-p2_ngqogr.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 19,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Jackets',
		productName: 'Camo Jacket',
		article: 'P-J-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183617/pentago/jackets/jacket-p3_vkxf9j.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 20,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Jackets',
		productName: 'Custom Jacket',
		article: 'P-J-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183617/pentago/jackets/jacket-p6_su4nn8.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 21,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Jackets',
		productName: 'Custom Jacket',
		article: 'P-J-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183618/pentago/jackets/jacket-p7_dgkwjf.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 22,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Shorts',
		productName: 'Casual Short',
		article: 'P-S-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183543/pentago/shorts/shorts-p1_y1jcut.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 23,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Shorts',
		productName: 'Casual Short',
		article: 'P-S-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183543/pentago/shorts/shorts-p2_m5d3t7.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 24,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Shorts',
		productName: 'Custom Short',
		article: 'P-S-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183543/pentago/shorts/shorts-p3_yfsxc4.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 25,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Shorts',
		productName: 'Sublimated Short',
		article: 'P-S-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183543/pentago/shorts/shorts-p4_sm38ci.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 26,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Shorts',
		productName: 'Custom Board Short',
		article: 'P-S-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183544/pentago/shorts/shorts-p6_zeiwja.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 27,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Shorts',
		productName: 'Custom Short',
		article: 'P-S-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183544/pentago/shorts/shorts-p9_h9bovp.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 28,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tshirts',
		productName: 'Plain Tshirt',
		article: 'P-TS-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183663/pentago/tshirts/tshirt-p3_u6za1q.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 29,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tshirts',
		productName: 'Plain Tshirt',
		article: 'P-TS-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183663/pentago/tshirts/tshirt-p1_sickee.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 30,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tshirts',
		productName: 'Custom Tshirt',
		article: 'P-TS-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183663/pentago/tshirts/tshirt-p2_jrrm9v.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 31,
		mainCategory: 'CASUALWEAR',
		subCategory: 'Tshirts',
		productName: 'Plain Tshirt',
		article: 'P-TS-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183664/pentago/tshirts/tshirt-p7_ee3lsn.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 32,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Fitness Short Women',
		article: 'P-FS-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183760/pentago/fitness-shorts/fitness-shorts-p2_vhqzzk.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 33,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Fitness Short Men with inner',
		article: 'P-FS-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183757/pentago/fitness-shorts/fitness-shorts-p12_q9vtku.png`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 34,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Gym Shorts',
		article: 'P-FS-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183757/pentago/fitness-shorts/fitness-shorts-p11_diedik.png`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 35,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Fitness Shorts',
		article: 'P-FS-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183756/pentago/fitness-shorts/fitness-shorts-p15_bfks28.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 36,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Women Shorts',
		article: 'P-FS-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183757/pentago/fitness-shorts/fitness-shorts-p1_lpqnhm.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 37,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Gym Shorts',
		article: 'P-FS-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183756/pentago/fitness-shorts/fitness-shorts-p13_m2psio.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 38,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Fitness Shorts',
		productName: 'Women Gym Shorts',
		article: 'P-FS-07',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183754/pentago/fitness-shorts/fitness-shorts-p4_tk9vg2.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 39,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Plain Legging',
		article: 'P-L-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183797/pentago/leggings/legging-p1_u6soew.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 40,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Plain Legging',
		article: 'P-L-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183796/pentago/leggings/legging-p6_gggbr6.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 41,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Tie Dye Legging',
		article: 'P-L-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183796/pentago/leggings/legging-p5_ghyhgg.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 42,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Tie Dye Legging',
		article: 'P-L-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183796/pentago/leggings/legging-p4_f6se61.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 43,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Tie Dye Legging',
		article: 'P-L-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183796/pentago/leggings/legging-p3_qtspa0.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 44,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Leggings',
		productName: 'Plain Legging',
		article: 'P-L-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183795/pentago/leggings/legging-p2_j3mtvx.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 45,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Tank Top',
		productName: 'Plain Tank Top',
		article: 'P-T-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183836/pentago/tanktops/tanktop-p4_x6fllv.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 46,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Tank Top',
		productName: 'Custom tank Top',
		article: 'P-T-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183836/pentago/tanktops/tanktop-p5_anlveg.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 47,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Tank Top',
		productName: 'Camo tank Top',
		article: 'P-T-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183835/pentago/tanktops/tanktop-p3_xiaf4a.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 48,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Tank Top',
		productName: 'Custom tank Top',
		article: 'P-T-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183835/pentago/tanktops/tanktop-p1_zbwhfa.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 49,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Activewear Set',
		productName: 'Plain Activewear Set',
		article: 'P-A-01',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183715/pentago/activewear-set/activewear-set-p3_xwg7c6.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 50,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Activewear Set',
		productName: 'Plain Activewear Set',
		article: 'P-A-02',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183713/pentago/activewear-set/activewear-set-p8_kezel7.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 51,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Activewear Set',
		productName: 'Plain Activewear Set',
		article: 'P-A-03',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183713/pentago/activewear-set/activewear-set-p7_uehmvt.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 52,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Activewear Set',
		productName: 'Sublimated Activewear Set',
		article: 'P-A-04',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183713/pentago/activewear-set/activewear-set-p4_kedkuz.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 53,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Activewear Set',
		productName: 'Activewear Set',
		article: 'P-A-05',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183713/pentago/activewear-set/activewear-set-p2_zywiir.jpg`,
		subCategoryImg: `${casualImage}`,
	},
	{
		id: 54,
		mainCategory: 'ACTIVEWEAR',
		subCategory: 'Activewear Set',
		productName: 'Activewear Set',
		article: 'P-A-06',
		productImg: `https://res.cloudinary.com/dpw1bckje/image/upload/v1690183713/pentago/activewear-set/activewear-set-p1_rmp74o.jpg`,
		subCategoryImg: `${casualImage}`,
	},
];

export default sliderItems;
export { navigation, productsDropdown, popularProducts, subCat, HoodieList, allProducts, ReviewData, finalData };
